server:
  port: 8081
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.37.4
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hello: 12345
